config/routes.rb
TestApp::Application.routes.draw do
  get "home_page/show"

  resources :some_models

  root :to => 'home_page#show'

end

app/models/some_model.rb
class SomeModel < ActiveRecord::Base
  attr_accessible :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_page_controller.rb
class HomePageController < ApplicationController
  def show
  end
end

app/controllers/some_models_controller.rb
class SomeModelsController < ApplicationController
  # GET /some_models
  # GET /some_models.json
  def index
    @some_models = SomeModel.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @some_models }
    end
  end

  # GET /some_models/1
  # GET /some_models/1.json
  def show
    @some_model = SomeModel.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @some_model }
    end
  end

  # GET /some_models/new
  # GET /some_models/new.json
  def new
    @some_model = SomeModel.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @some_model }
    end
  end

  # GET /some_models/1/edit
  def edit
    @some_model = SomeModel.find(params[:id])
  end

  # POST /some_models
  # POST /some_models.json
  def create
    @some_model = SomeModel.new(params[:some_model])

    respond_to do |format|
      if @some_model.save
        format.html { redirect_to @some_model, notice: 'Some model was successfully created.' }
        format.json { render json: @some_model, status: :created, location: @some_model }
      else
        format.html { render action: "new" }
        format.json { render json: @some_model.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /some_models/1
  # PUT /some_models/1.json
  def update
    @some_model = SomeModel.find(params[:id])

    respond_to do |format|
      if @some_model.update_attributes(params[:some_model])
        format.html { redirect_to @some_model, notice: 'Some model was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @some_model.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /some_models/1
  # DELETE /some_models/1.json
  def destroy
    @some_model = SomeModel.find(params[:id])
    @some_model.destroy

    respond_to do |format|
      format.html { redirect_to some_models_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_page_helper.rb
module HomePageHelper
end

app/helpers/some_models_helper.rb
module SomeModelsHelper
end

app/views/home_page/show.html.haml
<h1>Hello!</h1>
<p>What's your name?<p>
<input placeholder='First Name'></input>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TestApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/some_models/_form.html.erb
<%= form_for(@some_model) do |f| %>
  <% if @some_model.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@some_model.errors.count, "error") %> prohibited this some_model from being saved:</h2>

      <ul>
      <% @some_model.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/some_models/edit.html.erb
<h1>Editing some_model</h1>

<%= render 'form' %>

<%= link_to 'Show', @some_model %> |
<%= link_to 'Back', some_models_path %>

app/views/some_models/index.html.erb
<h1>Listing some_models</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @some_models.each do |some_model| %>
  <tr>
    <td><%= some_model.name %></td>
    <td><%= link_to 'Show', some_model %></td>
    <td><%= link_to 'Edit', edit_some_model_path(some_model) %></td>
    <td><%= link_to 'Destroy', some_model, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Some model', new_some_model_path %>

app/views/some_models/new.html.erb
<h1>New some_model</h1>

<%= render 'form' %>

<%= link_to 'Back', some_models_path %>

app/views/some_models/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @some_model.name %>
</p>


<%= link_to 'Edit', edit_some_model_path(@some_model) %> |
<%= link_to 'Back', some_models_path %>